name: "openwebui"
displayName: "Open WebUI"
description: "OpenWebUI is a sleek, open-source web interface for interacting with local or remote large language models (LLMs). It offers a modern, chat-style user experience, supports multiple models and users, and includes features like prompt history, persona presets, and markdown rendering. Designed for privacy and flexibility, it's ideal for self-hosted AI chat deployments."
category: "AI"
tags: ["LLM", "Web UI"]

chart:
  repoURL: "https://gitlab.com/api/v4/projects/54152051/packages/helm/devel"
  chartName: "open-webui"

logoURL: "https://artifacthub.io/image/53d07d19-9402-43d6-8619-fffa5683299e@2x"

versions:
  - chartVersion: "7.0.1"
    appVersion: "0.6.18"
    schemaFile: "schema.json"
    valuesFile: "values.yaml"