---
observ-edge:
  observVlmServiceUrl: https://visionai.linkervision.com/observ/observ-vlm-service
  offline: false
  dns: no-webrtc

  edgeAgent:
    address: https://no/
    name: ""
    workspace: ""
    prometheus: http://prometheus-kube-prometheus-prometheus.monitor:9090
    agentOrganization: Vision AI
    turnServerUrl: ""
    turnUsername: ""
    turnPassword: ""

  image:
    cr: observcr.azurecr.io
    tag: "3.9.4"

  mediaProviderUrl: https://visionai.linkervision.com/observ/media-provider
  ingressClassName: public

  streamAgent:
    broker: mqtt
    mqttHost: mqtt-prod.visionai.linkervision.com
    mqttPort: 1883
    mqttPassword: ""
    mqttTopic: ""
    mqttUser: ""
    deviceId: ""
    use_minio: false

  webServerUrl: https://visionai.linkervision.com/observ/
  webUiUrl: https://visionai.linkervision.com/observ/

  registry_url: observcr.azurecr.io

  mctPostprocessor:
    enable: false
    kafkaHost: kafka
    kafkaPort: 9092
    kafkaTopicPatterns: mdx-rtls-*,mdx-its-*
    worksapce: ""

  registry_username: ""
  registry_password: ""
