name: "kai"
displayName: "KAI Scheduler"
description: "KAI Scheduler is a robust, efficient, and scalable Kubernetes scheduler that optimizes GPU resource allocation for AI and machine learning workloads."
category: "Infrastructure"
tags: ["workflow"]

chart:
  repoURL: "oci://ghcr.io/nvidia/kai-scheduler"
  chartName: "kai-scheduler"

logoURL: ""

versions:
  - chartVersion: "v0.7.11"
    appVersion: "v0.7.11"
    valuesFile: "values.yaml"