replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.21.0-debian-10-r0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hostname: nginx.local
  path: /
  tls: false
