--- 
observ-edge:
  observVlmServiceUrl: https://visionai.linkervision.ai/observ/observ-vlm-service
  offline: false
  dns: 'no'

  edgeAgent:
    address: https://no/
    name: vm-d
    workspace: 48df843d-42b1-496f-b689-a711dd6bf8ec
    prometheus: http://prometheus-kube-prometheus-prometheus.monitor:9090
    agentOrganization: Vision AI
    turnServerUrl: ''
    turnUsername: ''
    turnPassword: ''

  image:
    cr: observcr.azurecr.io
    tag: 3.9.4

  mediaProviderUrl: https://visionai.linkervision.com/observ/media-provider
  ingressClassName: public

  streamAgent:
    broker: mqtt
    mqttHost: mqtt-prod.visionai.linkervision.com
    mqttPort: 1883
    mqttPassword: ""
    mqttTopic: 48df843d-42b1-496f-b689-a711dd6bf8ec
    mqttUser: ed78007a-bd47-485c-82db-66f69b4afd33
    deviceId: 48df843d-42b1-496f-b689-a711dd6bf8ec
    use_minio: false

  webServerUrl: https://visionai.linkervision.com/observ/
  webUiUrl: https://visionai.linkervision.com/observ/

  registry_url: observcr.azurecr.io

  mctPostprocessor:
    enable: false
    kafkaHost: kafka
    kafkaPort: 9092
    kafkaTopicPatterns: mdx-rtls-*,mdx-its-*
    worksapce: 48df843d-42b1-496f-b689-a711dd6bf8ec

  registry_username: ""
  registry_password: ""