name: "postgresql"
displayName: "PostgreSQL"
description: "Open source relational database for transactional and analytical workloads"
category: "Databases"
tags: ["postgres", "sql", "database"]

chart:
  repoURL: "https://charts.bitnami.com/bitnami"
  chartName: "postgresql"

logoURL: "https://artifacthub.io/image/371d5e57-34c4-46ef-909e-658c1502ced8@1x"

versions:
  - chartVersion: "13.2.20"
    appVersion: "16.2.0" 
    schemaFile: "schema.json"
    valuesFile: "values.yaml"
  - chartVersion: "16.7.19"
    appVersion: "17.5.0"
    schemaFile: "schema.json"
    valuesFile: "values.yaml"
