name: "postgresql"
displayName: "PostgreSQL"
description: "Open source relational database for transactional and analytical workloads"
category: "Databases"
tags: ["postgres", "sql", "database"]

chart:
  repoURL: "https://charts.bitnami.com/bitnami"
  chartName: "postgresql"

logoURL: "https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png"

versions:
  - chartVersion: "13.2.20"
    appVersion: "16.2.0" 
    schemaFile: "schema.json"
    valuesFile: "values.yaml"
  - chartVersion: "12.1.0"
    appVersion: "15.1.0"
    schemaFile: "schema.json"
    valuesFile: "values.yaml"
