name: "meta-llama-3-8b-nim"
displayName: "Meta-Llama-3-8B  [NIM]"
description: "Llama 3 is Meta’s family of large language models—available in 8 B and 70 B parameter sizes—and offered as an NVIDIA NIM model. Both sizes use Grouped-Query Attention for faster inference, and the instruction-tuned versions excel in dialogue tasks, outperforming many open-source chat models on common benchmarks."
category: "AI"
tags: ["chat", "8b", "llama"]

chart:
  repoURL: "https://gitlab.com/MohanDhandapani/avcs/-/raw/main"
  chartName: "llama3-8b-helm"

logoURL: "https://cdn-avatars.huggingface.co/v1/production/uploads/646cf8084eefb026fb8fd8bc/oCTqufkdTkjyGodsx1vo1.png"

versions:
  - chartVersion: "0.1.0"
    appVersion: "0.6.18"
    schemaFile: "schema.json"
    valuesFile: "values.yaml"